name: Sync Repo
on: 
  schedule:
    - cron: '0 14 * * *'
    # scheduled for 22:00 GMT+8 everyday
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0
      - name: Setup committer
        run: |
          git config --global user.email "tuthanika@gmail.com"
          git config --global user.name "tuthanika"
      - name: Merge Upstream
        run: |
          set +x
          git remote add -f upstream "https://github.com/j-hc/revanced-magisk-module" &&
          git remote -v &&
          git branch --all &&
          git config --list &&
          git checkout main
          echo "Upstream log: "
          git log --graph --oneline upstream/main | head -n 30
          echo "Our log: "
          git log --graph --oneline main | head -n 10
          echo "Merge fork point: $(git merge-base --fork-point main upstream/main)"
          git merge upstream/main -m "AutoMerge-$(date '+%Y%m%d-%H%M%S')"
          git merge --abort || true;
          echo "After Rebase:"
          git log --graph --oneline main | head -n 30
          echo "Re-tagging main!"
          git checkout $(git rev-parse HEAD); git branch -f main HEAD; git checkout main
      #- name: Prepare to push  
      #  run: git branch -f main
      - name: Push changes
        run: git push https://${{ github.token }}@github.com/tuthanika/revanced-magisk-module.git
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
